### ISSUE TITLE
Exporter panic

### ISSUE THREAD

**Issue by hartfordfive** [rokett/Citrix-NetScaler-Exporter#35]
Citrix NetScaler Version: `NS12.1: Build 55.18.nc`

When running the exporter, it randomly panics with a message such as this one:
```
level=error ts=2020-02-25T23:32:33.678889564Z caller=collector.go:379 app=Citrix-NetScaler-Exporter bind_port=9280 version=v4.3.0 build=197c8bc481b993e4a37d23cab563d8d07a16a456 msg="read failed: 404 Not Found ({ \"errorcode\": 258, \"message\": \"No such resource [serviceGroupName, _SF_ServiceGRP]\", \"severity\": \"ERROR\" })"
panic: runtime error: index out of range

goroutine 583 [running]:
github.com/rokett/citrix-netscaler-exporter/collector.(*Exporter).Collect(0xc00036a400, 0xc000264540)
        C:/Users/nickellsa/go/src/github.com/rokett/citrix-netscaler-exporter/collector/collector.go:382 +0x48f3
github.com/rokett/citrix-netscaler-exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc0003eafd0, 0xc000264540, 0x7e9020, 0xc00036a400)
        C:/Users/nickellsa/go/src/github.com/rokett/citrix-netscaler-exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:433 +0x61
created by github.com/rokett/citrix-netscaler-exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        C:/Users/nickellsa/go/src/github.com/rokett/citrix-netscaler-exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:431 +0x302
```

**Comment by rokett** [comment]
I'm unable to replicate this.  It kinda looks like between pulling a list of service groups, and trying to range over them, that one of them disappears.  Is that likely?

**Comment by rokett** [comment]
If and when you can replicate this, feel free to re-open the issue.  For now I'll close it as I can't replicate the problem.
